# Generated by Django 3.1.6 on 2021-04-03 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Display_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display_dioganal', models.FloatField()),
                ('ram', models.IntegerField()),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.brand')),
                ('display_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.display_type')),
            ],
        ),
    ]
